name: Auto Tag and Changelog

on:
  # Disable automatic runs - manual only for now
  workflow_dispatch:
    inputs:
      create_tag:
        description: 'Create new tag'
        required: true
        default: 'false'
        type: choice
        options:
        - 'true'
        - 'false'

jobs:
  tag-and-changelog:
    runs-on: ubuntu-latest
    if: github.event.inputs.create_tag == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Manual tagging notice
        run: |
          echo "⚠️  AUTOMATED TAGGING DISABLED"
          echo "Manual changelog management is now active"
          echo "Tags should be created manually with proper semantic versioning"
