name: Auto Tag on Push
on:
  push:
    branches:
      - xp_core
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      - name: Create tag and push (verbose)
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          set -x
          TAG_NAME="auto-xp_core-$(date +'%Y%m%d')-$(git rev-parse --short HEAD)"
          git tag "$TAG_NAME"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin "$TAG_NAME"
